# Generated by Django 4.2 on 2026-01-08 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_department_user_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='class_name',
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=50)),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.timeslot')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendance',
            name='class_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.class'),
        ),
        migrations.AddField(
            model_name='student',
            name='classes',
            field=models.ManyToManyField(related_name='students', to='users.class'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'class_obj', 'date')},
        ),
    ]
